// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/lol_earlyduskbk.tga
gfx/env/lol_earlyduskdn.tga
gfx/env/lol_earlyduskft.tga
gfx/env/lol_earlydusklf.tga
gfx/env/lol_earlyduskrt.tga
gfx/env/lol_earlyduskup.tga
legends.wad
models/legends/enemies/bandit.mdl
models/legends/enemies/wolf1.mdl
models/legends/enemies/wolf2.mdl
models/legends/items/armor_bandit.mdl
models/legends/items/health_potion.mdl
models/legends/npc/rabbit.mdl
models/legends/npc/wizard1.mdl
models/legends/props/null.mdl
models/legends/props/trees.mdl
models/legends/props/trees_small.mdl
models/legends/weapons/p_cl_healing_hands.mdl
models/legends/weapons/p_cl_mace.mdl
models/legends/weapons/p_staff.mdl
models/legends/weapons/p_vial.mdl
models/legends/weapons/p_wa_sword.mdl
models/legends/weapons/v_cl_healing_hands.mdl
models/legends/weapons/v_cl_mace.mdl
models/legends/weapons/v_staff.mdl
models/legends/weapons/v_vial.mdl
models/legends/weapons/v_wa_sword.mdl
models/legends/weapons/w_cl_healing_hands.mdl
models/legends/weapons/w_cl_mace.mdl
models/legends/weapons/w_staff.mdl
models/legends/weapons/w_staffammo.mdl
models/legends/weapons/w_vial.mdl
models/legends/weapons/w_wa_sword.mdl
models/player/legends_cleric/legends_cleric.bmp
models/player/legends_cleric/legends_cleric.mdl
models/player/legends_rogue/legends_rogue.bmp
models/player/legends_rogue/legends_rogue.mdl
models/player/legends_warrior/legends_warrior.bmp
models/player/legends_warrior/legends_warrior.mdl
models/player/legends_wizard/legends_wizard.bmp
models/player/legends_wizard/legends_wizard.mdl
sound/legends/birds.wav
sound/legends/dopefish/burb.wav
sound/legends/dopefish/swim1.wav
sound/legends/dopefish/swim2.wav
sound/legends/dopefish/swim3.wav
sound/legends/dopefish/swim4.wav
sound/legends/goblin/pit_drone_communicate1.wav
sound/legends/goblin/pit_drone_communicate2.wav
sound/legends/goblin/pit_drone_communicate3.wav
sound/legends/goblin/pit_drone_communicate4.wav
sound/legends/goblin/pit_drone_die1.wav
sound/legends/goblin/pit_drone_die2.wav
sound/legends/goblin/pit_drone_die3.wav
sound/legends/goblin/pit_drone_hunt1.wav
sound/legends/goblin/pit_drone_hunt2.wav
sound/legends/goblin/pit_drone_hunt3.wav
sound/legends/goblin/pit_drone_idle1.wav
sound/legends/goblin/pit_drone_idle2.wav
sound/legends/goblin/pit_drone_idle3.wav
sound/legends/goblin/pit_drone_pain1.wav
sound/legends/goblin/pit_drone_pain2.wav
sound/legends/goblin/pit_drone_pain3.wav
sound/legends/goblin/pit_drone_pain4.wav
sound/legends/lol_pompeus.wav
sound/legends/materials.txt
sound/legends/null.wav
sound/legends/ogre/ag_alert1.wav
sound/legends/ogre/ag_alert2.wav
sound/legends/ogre/ag_alert3.wav
sound/legends/ogre/ag_alert4.wav
sound/legends/ogre/ag_alert5.wav
sound/legends/ogre/ag_attack1.wav
sound/legends/ogre/ag_attack2.wav
sound/legends/ogre/ag_attack3.wav
sound/legends/ogre/ag_die1.wav
sound/legends/ogre/ag_die2.wav
sound/legends/ogre/ag_die3.wav
sound/legends/ogre/ag_die4.wav
sound/legends/ogre/ag_die5.wav
sound/legends/ogre/ag_idle1.wav
sound/legends/ogre/ag_idle2.wav
sound/legends/ogre/ag_idle3.wav
sound/legends/ogre/ag_idle4.wav
sound/legends/ogre/ag_idle5.wav
sound/legends/ogre/ag_pain1.wav
sound/legends/ogre/ag_pain2.wav
sound/legends/ogre/ag_pain3.wav
sound/legends/ogre/ag_pain4.wav
sound/legends/ogre/ag_pain5.wav
sound/legends/ogre/step1.wav
sound/legends/ogre/step2.wav
sound/legends/queen/die.wav
sound/legends/queen/hiss.wav
sound/legends/queen/hurt.wav
sound/legends/queen/step1.wav
sound/legends/queen/step2.wav
sound/legends/queen/step3.wav
sound/legends/weapons/cbar_hit1.wav
sound/legends/weapons/cbar_hit2.wav
sound/legends/weapons/cbar_hitbod1.wav
sound/legends/weapons/cbar_hitbod2.wav
sound/legends/weapons/cbar_hitbod3.wav
sound/legends/weapons/cbar_miss1.wav
sound/legends/weapons/egon_off1.wav
sound/legends/weapons/egon_run3.wav
sound/legends/weapons/egon_windup2.wav
sound/legends/weapons/gauss2.wav
sound/legends/weapons/medshot4.wav
sound/legends/weapons/pulsemachine.wav
sound/legends/weapons/pwrench_big_hit1.wav
sound/legends/weapons/pwrench_big_hit2.wav
sound/legends/weapons/pwrench_big_hitbod1.wav
sound/legends/weapons/pwrench_big_hitbod2.wav
sound/legends/weapons/pwrench_big_miss.wav
sound/legends/weapons/pwrench_hit1.wav
sound/legends/weapons/pwrench_hit2.wav
sound/legends/weapons/pwrench_hitbod1.wav
sound/legends/weapons/pwrench_hitbod2.wav
sound/legends/weapons/pwrench_hitbod3.wav
sound/legends/weapons/pwrench_miss1.wav
sound/legends/weapons/pwrench_miss2.wav
sound/legends/wolf/claw_miss1.wav
sound/legends/wolf/claw_miss2.wav
sound/legends/wolf/claw_strike1.wav
sound/legends/wolf/claw_strike2.wav
sound/legends/wolf/claw_strike3.wav
sound/legends/wolf/zo_alert10.wav
sound/legends/wolf/zo_alert20.wav
sound/legends/wolf/zo_alert30.wav
sound/legends/wolf/zo_attack1.wav
sound/legends/wolf/zo_attack2.wav
sound/legends/wolf/zo_idle1.wav
sound/legends/wolf/zo_idle2.wav
sound/legends/wolf/zo_idle3.wav
sound/legends/wolf/zo_idle4.wav
sound/legends/wolf/zo_pain1.wav
sound/legends/wolf/zo_pain2.wav
sprites/legends/fire_locked.spr
