// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/REvil/Chris.mdl
models/REvil/Forrest.mdl
models/REvil/hungerzork.mdl
models/REvil/Hunter.mdl
models/REvil/IModels/bluebook.mdl
models/REvil/IModels/book.mdl
models/REvil/IModels/key.mdl
models/REvil/IModels/keyt.mdl
models/REvil/IModels/redbook.mdl
models/REvil/IModels/w_crowbar.mdl
models/REvil/IModels/w_crowbart.mdl
models/REvil/IModels/w_kevlar.mdl
models/REvil/Ken.mdl
models/REvil/megasquid.mdl
models/REvil/megasquid01.mdl
models/REvil/megasquidt.mdl
models/REvil/osprey_crashed.mdl
models/REvil/Rich.mdl
models/REvil/szombie.mdl
models/REvil/szombiet.mdl
models/REvil/tyrant.mdl
models/REvil/umbrella1.mdl
models/REvil/WModels/1911/p_9mmhandgun.mdl
models/REvil/WModels/1911/v_9mmhandgun.mdl
models/REvil/WModels/1911/w_9mmhandgun.mdl
models/REvil/WModels/357/v_357.mdl
models/REvil/WModels/AK74U/P_Uzi.mdl
models/REvil/WModels/AK74U/v_uzi.mdl
models/REvil/WModels/AK74U/w_uzi.mdl
models/REvil/WModels/BravoMP5/p_9mmAR.mdl
models/REvil/WModels/BravoMP5/v_9mmAR.mdl
models/REvil/WModels/BravoMP5/w_9mmAR.mdl
models/REvil/WModels/Grenade/v_grenade.mdl
models/REvil/WModels/Knife/p_crowbar.mdl
models/REvil/WModels/Knife/v_crowbar.mdl
models/REvil/WModels/Knife/w_crowbar.mdl
models/REvil/WModels/M3/v_shotgun.mdl
models/REvil/WModels/Medkit/v_medkit.mdl
models/REvil/WModels/mgun/v_minigun.mdl
models/REvil/WModels/Scout/p_crossbow.mdl
models/REvil/WModels/Scout/v_crossbow.mdl
models/REvil/WModels/Scout/w_crossbow.mdl
models/REvil/WModels/Socom/p_9mmhandgun.mdl
models/REvil/WModels/Socom/v_9mmhandgun.mdl
models/REvil/WModels/Socom/w_9mmhandgun.mdl
models/REvil/zombie.mdl
models/REvil/zombie01.mdl
models/REvil/zombie02.mdl
models/REvil/zombie03.mdl
models/REvil/zombiet.mdl
sound/REvil/Bossbattle.wav
sound/REvil/countdown.wav
sound/REvil/hungerzork/ag_alert1.wav
sound/REvil/hungerzork/ag_alert2.wav
sound/REvil/hungerzork/ag_alert3.wav
sound/REvil/hungerzork/ag_alert4.wav
sound/REvil/hungerzork/ag_alert5.wav
sound/REvil/hungerzork/ag_attack1.wav
sound/REvil/hungerzork/ag_attack2.wav
sound/REvil/hungerzork/ag_attack3.wav
sound/REvil/hungerzork/ag_die1.wav
sound/REvil/hungerzork/ag_die2.wav
sound/REvil/hungerzork/ag_die3.wav
sound/REvil/hungerzork/ag_die4.wav
sound/REvil/hungerzork/ag_die5.wav
sound/REvil/hungerzork/ag_idle1.wav
sound/REvil/hungerzork/ag_idle2.wav
sound/REvil/hungerzork/ag_idle3.wav
sound/REvil/hungerzork/ag_idle4.wav
sound/REvil/hungerzork/ag_idle5.wav
sound/REvil/hungerzork/ag_pain1.wav
sound/REvil/hungerzork/ag_pain2.wav
sound/REvil/hungerzork/ag_pain3.wav
sound/REvil/hungerzork/ag_pain4.wav
sound/REvil/hungerzork/ag_pain5.wav
sound/REvil/hungerzork/leftfoot2.wav
sound/REvil/hungerzork/leftfoot4.wav
sound/REvil/hungerzork/rightfoot1.wav
sound/REvil/hungerzork/rightfoot3.wav
sound/REvil/moonlightsonata.wav
sound/REvil/re1music.wav
sound/REvil/re2_hunk.wav
sound/REvil/RESuperzombie/claw_miss1.wav
sound/REvil/RESuperzombie/claw_miss2.wav
sound/REvil/RESuperzombie/claw_strike1.wav
sound/REvil/RESuperzombie/claw_strike2.wav
sound/REvil/RESuperzombie/claw_strike3.wav
sound/REvil/RESuperzombie/zo_alert10.wav
sound/REvil/RESuperzombie/zo_alert20.wav
sound/REvil/RESuperzombie/zo_alert30.wav
sound/REvil/RESuperzombie/zo_attack1.wav
sound/REvil/RESuperzombie/zo_attack2.wav
sound/REvil/RESuperzombie/zo_idle1.wav
sound/REvil/RESuperzombie/zo_idle2.wav
sound/REvil/RESuperzombie/zo_idle3.wav
sound/REvil/RESuperzombie/zo_idle4.wav
sound/REvil/RESuperzombie/zo_pain1.wav
sound/REvil/RESuperzombie/zo_pain2.wav
sound/REvil/REzombie/claw_miss1.wav
sound/REvil/REzombie/claw_miss2.wav
sound/REvil/REzombie/claw_strike1.wav
sound/REvil/REzombie/claw_strike2.wav
sound/REvil/REzombie/claw_strike3.wav
sound/REvil/REzombie/zo_alert10.wav
sound/REvil/REzombie/zo_alert20.wav
sound/REvil/REzombie/zo_alert30.wav
sound/REvil/REzombie/zo_attack1.wav
sound/REvil/REzombie/zo_attack2.wav
sound/REvil/REzombie/zo_idle1.wav
sound/REvil/REzombie/zo_idle2.wav
sound/REvil/REzombie/zo_idle3.wav
sound/REvil/REzombie/zo_idle4.wav
sound/REvil/REzombie/zo_pain1.wav
sound/REvil/REzombie/zo_pain2.wav
sound/REvil/thunder_clap.wav
sound/REvil/Tyrant/_period.wav
sound/REvil/Tyrant/primalscreaming.wav
sound/REvil/Tyrant/role4_idle1.wav
sound/REvil/Tyrant/role4_idle2.wav
sound/REvil/Tyrant/role4_idle3.wav
sound/REvil/Tyrant/role7_die2.wav
sound/REvil/Tyrant/role7_die3.wav
sound/REvil/Tyrant/role7_die4.wav
sound/REvil/Tyrant/role7_spawn1.wav
sound/REvil/Tyrant/role7_wound1.wav
sound/REvil/tyrantburst1.wav
sound/REvil/weapon/socom/clipin.wav
sound/REvil/weapon/socom/clipout.wav
sound/REvil/weapon/socom/glock-fire.wav
sound/REvil/weapon/socom/slideback.wav
sound/REvil/zombieattack2.wav
sound/weapons/ak47_magin.wav
sound/weapons/ak47_magout.wav
sound/weapons/glaunchready.wav
sound/weapons/grenade_pin.wav
sound/weapons/m3_insertshell.wav
sound/weapons/m3_pump.wav
sound/weapons/mp5_clipin.wav
sound/weapons/mp5_clipout.wav
sound/weapons/mp5_slideback.wav
sound/weapons/scout_bolt.wav
sound/weapons/scout_clipin.wav
sound/weapons/scout_clipout.wav
sound/weapons/haleluja.wav