// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/Aftermath/Archvile.mdl
models/Aftermath/Hunter2.mdl
models/Aftermath/IModels/Adrenaline.mdl
models/Aftermath/IModels/forkey.mdl
models/Aftermath/IModels/key.mdl
models/Aftermath/IModels/toolbox.mdl
models/Aftermath/IModels/w_crowbar.mdl
models/Aftermath/IModels/w_crowbart.mdl
models/Aftermath/IModels/w_security.mdl
models/Aftermath/neptune.mdl
models/Aftermath/WModels/1911/p_9mmhandgun.mdl
models/Aftermath/WModels/1911/v_9mmhandgun.mdl
models/Aftermath/WModels/1911/w_9mmhandgun.mdl
models/Aftermath/WModels/357/v_357.mdl
models/Aftermath/WModels/Ak74u/P_Uzi.mdl
models/Aftermath/WModels/Ak74u/v_uzi.mdl
models/Aftermath/WModels/Ak74u/w_uzi.mdl
models/Aftermath/WModels/Knife/p_crowbar.mdl
models/Aftermath/WModels/Knife/v_crowbar.mdl
models/Aftermath/WModels/Knife/w_crowbar.mdl
models/Aftermath/WModels/M3/v_shotgun.mdl
models/Aftermath/WModels/Medkit/v_medkit.mdl
models/Aftermath/zombie.mdl
re.wad
re1_btm.wad
reco.wad
sound/ambience/fem_helpme.wav
sound/ambience/heartbeat.wav
sound/ambience/jxfirecamp.wav
sound/ambience/jxpowerdown.wav
sound/ambience/kissa_thunder3.wav
sound/ambience/mr_loudevil.wav
sound/ambience/re2music1.wav
sound/ambience/scaryass.wav
sound/ambience/UmbrellaLab.wav
sound/ambience/voxescapemessage.wav
sound/ambience/zombieattack3.wav
sound/REzombie/claw_miss1.wav
sound/REzombie/claw_miss2.wav
sound/REzombie/claw_strike1.wav
sound/REzombie/claw_strike2.wav
sound/REzombie/claw_strike3.wav
sound/REzombie/zo_alert10.wav
sound/REzombie/zo_alert20.wav
sound/REzombie/zo_alert30.wav
sound/REzombie/zo_attack1.wav
sound/REzombie/zo_attack2.wav
sound/REzombie/zo_idle1.wav
sound/REzombie/zo_idle2.wav
sound/REzombie/zo_idle3.wav
sound/REzombie/zo_idle4.wav
sound/REzombie/zo_pain1.wav
sound/REzombie/zo_pain2.wav
sound/weapons/ak47_magin.wav
sound/weapons/ak47_magout.wav
sound/weapons/m3_insertshell.wav
sound/weapons/m3_pump.wav
