// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/sc_egypt/baby_voltigore.mdl
models/sc_egypt/blackop_desert.mdl
models/sc_egypt/bullsquid.mdl
models/sc_egypt/bush1.mdl
models/sc_egypt/bush2.mdl
models/sc_egypt/crocodile.mdl
models/sc_egypt/garg.mdl
models/sc_egypt/hk_sandbags.mdl
models/sc_egypt/islave.mdl
models/sc_egypt/mummy_zomb.mdl
models/sc_egypt/opfor_desert.mdl
models/sc_egypt/p_knife.mdl
models/sc_egypt/p_squeak.mdl
models/sc_egypt/palm1A.mdl
models/sc_egypt/palm1B.mdl
models/sc_egypt/palm2.mdl
models/sc_egypt/scorpion.mdl
models/sc_egypt/v_knife.mdl
models/sc_egypt/v_squeak.mdl
models/sc_egypt/voltigore.mdl
models/sc_egypt/w_knife.mdl
models/sc_egypt/w_squeak.mdl
models/sc_egypt/Xen_grass1.mdl
models/sc_egypt/Xen_grass2.mdl
sc_egypt.wad
sound/sc_royals/mummy_alert1.wav
sound/sc_royals/mummy_alert2.wav
sound/sc_royals/mummy_alert3.wav
sound/sc_royals/mummy_attack1.wav
sound/sc_royals/mummy_attack2.wav
sound/sc_royals/mummy_idle1.wav
sound/sc_royals/mummy_idle2.wav
sound/sc_royals/mummy_idle3.wav
sound/sc_royals/mummy_idle4.wav
sound/sc_royals/mummy_pain1.wav
sound/sc_royals/mummy_pain2.wav
